blog_blog_comment:
    resource: "@BlogBlogBundle/Controller/CommentController.php"
    type:     annotation

# app/config/routing.yml


blog_blog:
    resource: "@BlogBlogBundle/Resources/config/routing.yml"
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"